CREATE TABLE IF NOT EXISTS media_quality_samples (
    sample_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL,
    call_id CHAR(36) NOT NULL,
    media_session_id CHAR(36) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    caller_leg_id CHAR(36) NOT NULL,
    callee_leg_id CHAR(36) NOT NULL,
    sampled_at DATETIME(6) NOT NULL,
    caller_packets BIGINT UNSIGNED NOT NULL,
    caller_bytes BIGINT UNSIGNED NOT NULL,
    caller_lost BIGINT UNSIGNED NOT NULL,
    caller_reordered BIGINT UNSIGNED NOT NULL,
    caller_duplicates BIGINT UNSIGNED NOT NULL,
    caller_jitter_samples DOUBLE NOT NULL,
    caller_rtt_microseconds BIGINT UNSIGNED NOT NULL,
    caller_timed_out BOOLEAN NOT NULL,
    callee_packets BIGINT UNSIGNED NOT NULL,
    callee_bytes BIGINT UNSIGNED NOT NULL,
    callee_lost BIGINT UNSIGNED NOT NULL,
    callee_reordered BIGINT UNSIGNED NOT NULL,
    callee_duplicates BIGINT UNSIGNED NOT NULL,
    callee_jitter_samples DOUBLE NOT NULL,
    callee_rtt_microseconds BIGINT UNSIGNED NOT NULL,
    callee_timed_out BOOLEAN NOT NULL,
    one_way BOOLEAN NOT NULL,
    dropped_summaries BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (sample_id),
    KEY idx_media_quality_call_time (tenant_id, call_id, sampled_at),
    KEY idx_media_quality_session_time (media_session_id, sampled_at)
) ENGINE=InnoDB;
